import flet as ft

from components.page_header import PageHeader
from components.layout import Layout
from components.logo import Logo
from components.menu import MenuHeader, MenuBody, MenuTitle, MenuItem, MenuFooter
from components.title_bar import TitleBar


def HomeView(sub_pages: ft.Container):
    return ft.View(
        route='/index',
        controls=[
            Layout(
                aside=ft.Column(
                    expand=True,
                    controls=[
                        MenuHeader(
                            controls=[
                                Logo()
                            ]
                        ),
                        MenuBody(
                            controls=[
                                MenuTitle(
                                    title='Home',
                                ),
                                MenuItem(
                                    title='Overview',
                                    icon=ft.icons.HOME,
                                    path='/overview',
                                ),
                                MenuTitle(
                                    title='Apps',
                                ),
                                MenuItem(
                                    title='Chat',
                                    icon=ft.icons.CHAT,
                                    path='/chat',
                                ),
                                MenuItem(
                                    title='Users',
                                    icon=ft.icons.PEOPLE,
                                    controls=[
                                        MenuItem(
                                            title='Profile',
                                            path='/users/profile'
                                        ),
                                        MenuItem(
                                            title='Followers',
                                            path='/users/followers'
                                        ),
                                        MenuItem(
                                            title='Friends',
                                            path='/users/friends'
                                        ),
                                        MenuItem(
                                            title='Gallery',
                                            path='/users/gallery'
                                        )
                                    ]
                                ),
                                MenuItem(
                                    title='Invoice',
                                    icon=ft.icons.LIST,
                                    path='/invoice',
                                    controls=[
                                        MenuItem(
                                            title='List',
                                            path='/invoice/list'
                                        ),
                                        MenuItem(
                                            title='Create',
                                            path='/invoice/create'
                                        ),
                                        MenuItem(
                                            title='Detail',
                                            path='/invoice/detail'
                                        ),
                                        MenuItem(
                                            title='Edit',
                                            path='/invoice/edit'
                                        )
                                    ]
                                ),
                                MenuItem(
                                    title='Kanban',
                                    icon=ft.icons.SIGNPOST,
                                    path='/kanban'
                                ),
                                MenuItem(
                                    title='Notes',
                                    icon=ft.icons.NOTE,
                                    path='/notes'
                                ),
                                MenuItem(
                                    title='Calendar',
                                    icon=ft.icons.CALENDAR_MONTH,
                                    path='/calendar'
                                ),
                                MenuItem(
                                    title='Email',
                                    icon=ft.icons.MAIL,
                                    path='/email'
                                ),
                                MenuTitle(
                                    title='General',
                                ),
                                MenuItem(
                                    title='Settings',
                                    icon=ft.icons.SETTINGS,
                                    path='/settings',
                                ),
                                MenuTitle('Auth'),
                                MenuItem(
                                    title='Register',
                                    icon=ft.icons.PERSON_ADD,
                                    path='/register'
                                ),
                                MenuItem(
                                    title='Login',
                                    icon=ft.icons.LOGIN,
                                    path='/login'
                                ),
                                MenuItem(
                                    title='Logout',
                                    icon=ft.icons.LOGOUT,
                                    path='/logout'
                                )
                            ]
                        ),
                        MenuFooter(
                            avatar=ft.icons.PERSON,
                            title='Matthew',
                            sub_title='matthew@gmail.com'
                        )
                    ]
                ),
                header=PageHeader(
                    avatar='assets/avatar/avatar.png'
                ),
                body=sub_pages
            )
        ]
    )
